import MainContent from "./Components/MainContent/MainContent";
import SideNav from "./Components/SideNav/SideNav";

export const metadata = {
  title: "Kanban Task Manager",
  description: "Generated by create next app",
  icons: ["/images/kanban-board.webp"],
};

export default function Home() {
  return (
    <div class="h-screen w-full bg-[#FFFFFF]">
      <SideNav />
      <MainContent />
    </div>
  );
}
